name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DEVELOPER_DIR: /Applications/Xcode_16.1.app/Contents/Developer

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-docker-action@v4
      - name: Start SMB server
        run: docker compose up --detach
      - name: Run tests
        run: swift test
